In [4]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn import datasets

In [28]:
df=pd.read_csv("Iris.csv")

In [29]:
#IF DATASET IS IMPORT
#iris = datasets.load_iris()
#X = pd.DataFrame(iris.data, columns=iris.feature_names)
#y = pd.Series(iris.target, name='FlowerType')
#X.head()

In [31]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [38]:
#Standardize the Data
features = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']
x = df.loc[:, features].values
y = df.loc[:,['Species']].values
x= StandardScaler().fit_transform(x)
pd.DataFrame(data = x, columns = features).head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      -0.900681      1.032057      -1.341272     -1.312977
1      -1.143017     -0.124958      -1.341272     -1.312977
2      -1.385353      0.337848      -1.398138     -1.312977
3      -1.506521      0.106445      -1.284407     -1.312977
4      -1.021849      1.263460      -1.341272     -1.312977

In [22]:
#PCA Projection to 2D
pca = PCA(n_components=2)
principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1', 'principal component 2'])
principalDf.head(5)

   principal component 1  principal component 2
0              -2.264703               0.480027
1              -2.080961              -0.674134
2              -2.364229              -0.341908
3              -2.299384              -0.597395
4              -2.389842               0.646835

In [39]:
df[['Species']].head()

       Species
0  Iris-setosa
1  Iris-setosa
2  Iris-setosa
3  Iris-setosa
4  Iris-setosa

In [41]:
finalDf = pd.concat([principalDf, df[['Species']]], axis = 1)
finalDf.head(5)

   principal component 1  principal component 2      Species
0              -2.264703               0.480027  Iris-setosa
1              -2.080961              -0.674134  Iris-setosa
2              -2.364229              -0.341908  Iris-setosa
3              -2.299384              -0.597395  Iris-setosa
4              -2.389842               0.646835  Iris-setosa